package io.ruin.model.contracts.farming;

/**
 * @author Greco
 * @since 11/24/2021
 */
public enum FarmingContractType {

    NONE,

    /**
     * EASY CONTRACTS (45 FARMING)
     */
    POTATOES, MARIGOLD, ONIONS, CABBAGES, REDBERRIES, ROSEMARY, TOMATOES,
    SWEETCORN, CADAVABERRIES, NASTIRTIUM, WOAD, LIMPWURT, STRAWBERRIES, DWELLBERRIES,
    JANGERBERRIES, CACTUS, GUAM, MARRENTILL, OAK_TREE, TARROMIN, HARRALANDER, WILLOW_TREE,
    RANARR, TOADFLAX, IRIT, MAPLE_TREE, AVANTOE, APPLE_TREE, BANANA_TREE, ORANGE_TREE, CURRY_TREE,

    /**
     * MEDIUM CONTRACTS (65 FARMING)
     */
    WATERMELONS, KWUARM, WHITE_LILY, WHITEBERRIES, YEW_TREE, SNAPE_GRASS, SNAPDRAGON, POTATO_CACTUS,
    CADANTINE, POISON_IVY, LANTADYME, MAGIC_TREE, PINEAPPLE_PLANT, PAPAYA_PLANT, PALM_TREE,

    /**
     * HARD CONTRACTS (85 FARMING)
     */
    DWARF_WEED, DRAGONFRUIT_TREE, CELASTRUS_TREE, TORSTOL, REDWOOD_TREE,


}
